language: node_js
node_js:
  - "lts/*"
branches:
  only:
  - master
cache:
  directories:
  - node_modules
  yarn: true
before_install:
- export TZ='Asia/Shanghai'  # 设置时区
install:
- yarn install
script:
- yarn docs:build
deploy:
  provider: pages
  skip-cleanup: true
  ## github-token: $GITHUB_TOKEN
  github-token: $GITHUB_TOKEN
  local-dir: ./docs/.vuepress/dist/ ## 根据情况自定义到静态文件输出目录
  target-branch: master
  verbose: true
  keep-history: true
  on:
    branch: gh-pages
branches:
  only:

    - gh-pages

 